### ISSUE TITLE
Installation unter Contao 4.9.1 funktioniert nicht

### ISSUE THREAD

**Issue by Schmidty2** [heimrichhannot/contao-twentytwenty-bundle#4]
Die Installation in einer neuen Contao 4.9.1-Instanz ist nicht möglich.
Provider: All-Inkl Business, PHP 7.3
Ausgabe des Contao-Managers:
[Error - Twenty.txt](https://github.com/heimrichhannot/contao-twentytwenty-bundle/files/4348754/Error.-.Twenty.txt)

**Comment by koertho** [comment]
@Schmidty2 Das sollte in Version 1.1 behoben sein. Würde mich über Feedback freuen.

**Comment by Schmidty2** [comment]
@koertho Danke für die schnelle Rückmeldung.
Der Fehler beim installierren bzw. dem Update ist jetzt weg, aber die Extension läuft nicht, die Fotos werden untereinander dargestellt.

**Comment by koertho** [comment]
@Schmidty2 Das klingt, als würde die Assets nicht richtig eingebunden. Kannst du das mal gegenprüfen?

**Comment by Schmidty2** [comment]
@koertho So wie ich es sehe, wird alles ordnungsgemäß geladen.
Ich habe das Ganze noch einmal in einer neuen Testinstallation ausprobiert (Contao 4.9.1 und TwentyTwenty, kein Theme etc), auch da das gleiche Problem.
Den Zugang zur Testinstallation kann ich gerne per E-Mail bereitstellen.

**Comment by Schmidty2** [comment]
Hallo,
konntet Ihr das Ganze schon anschauen. Auch in einer neuen Installation bei einem anderen Provider das selbe Problem: Die Bilder werden untereinander dargestellt.

**Comment by koertho** [comment]
@Schmidty2 Sorry, wir sind gerade sehr ausgelastet und das Bundle ist in kaum einem Projekt dabei, daher sind wir noch nicht dazu gekommen. Was das schließen absicht?
Könntest du schauen, ob sich die Sintax geändert hat?

**Comment by Schmidty2** [comment]
@koertho Das schließen war versehentlich - sorry
Ich habe heute noch einmal alles angeschaut, aber keinen Fehler gefunden.
Einen Link zur Testseite kann ich gerne per PN zukommen lassen.
Da ich das Ganze demnächst in einem Projekt benötige wäre auch eine finanzielle Unterstützung möglich.

**Comment by koertho** [comment]
@Schmidty2 Bug sollte in in 1.2 behoben sein. Die Assets wurden nicht geladen.

**Comment by Schmidty2** [comment]
@koertho Danke - funktioniert jetzt wie gewünscht.
Ich schließe das Ticket :-)
